
'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating a comprehensive health report.
 *
 * The flow takes a user's health data as input and uses a language model to create a
 * detailed report, including a summary, risk analysis, and actionable recommendations.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateHealthReportInputSchema = z.object({
  healthData: z
    .string()
    .describe('A summary of the user\'s health data, including vitals, conditions, medications, and allergies.'),
});
export type GenerateHealthReportInput = z.infer<
  typeof GenerateHealthReportInputSchema
>;

const GenerateHealthReportOutputSchema = z.object({
  reportContent: z
    .string()
    .describe(
      'The full, formatted health report, including an overall summary, risk factor analysis, and personalized recommendations. The report should be formatted as markdown.'
    ),
});
export type GenerateHealthReportOutput = z.infer<
  typeof GenerateHealthReportOutputSchema
>;

export async function generateHealthReport(
  input: GenerateHealthReportInput
): Promise<GenerateHealthReportOutput> {
  return generateHealthReportFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateHealthReportPrompt',
  input: {schema: GenerateHealthReportInputSchema},
  output: {schema: GenerateHealthReportOutputSchema},
  prompt: `You are an AI Health and Wellness Advisor. Your task is to generate a comprehensive and easy-to-understand health report in markdown format based on the user-provided data.

  User's Health Data:
  "{{{healthData}}}"

  Generate a report with the following sections:
  1.  **Overall Health Summary:** Provide a brief, high-level overview of the user's current health status based on the data.
  2.  **Key Health Metrics Analysis:** Break down the provided data (e.g., blood pressure, heart rate, weight). Explain what each metric means and whether it falls within a healthy range.
  3.  **Potential Risk Factors:** Identify any potential health risks based on the combination of lifestyle, conditions, and vitals.
  4.  **Personalized Recommendations:** Offer clear, actionable, and positive recommendations for improving or maintaining health. Suggestions could include diet, exercise, and when to consult a healthcare professional.

  IMPORTANT: Your response MUST include a prominent disclaimer at the end stating: "This report is generated by an AI and is for informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition."

  Structure your entire output to fit into the 'reportContent' field of the JSON object.
  `,
});

const generateHealthReportFlow = ai.defineFlow(
  {
    name: 'generateHealthReportFlow',
    inputSchema: GenerateHealthReportInputSchema,
    outputSchema: GenerateHealthReportOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
