
// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as it will be overwritten.
//
// Your web app's Firebase configuration
// For more information on how to use this object, see
// https://firebase.google.com/docs/web/setup#available-libraries

// IMPORTANT: Do not remove or change any of the values below!
// These values are using environment variables provided by Firebase App Hosting.
// They will be automatically populated based on the connected Firebase project.

export const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  measurementId: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
};
